name: conduit_isolate_exec
version: 3.0.11
homepage: https://github.com/conduit-dart/isolate-exec
description: This library contains types that allow for executing code in a spawned isolate, perhaps with additional imports.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  path: ^1.8.0
  reflectable: ^3.0.4
dev_dependencies:
  build_runner:
  build_test:
  lint: ^1.5.3
  test: ^1.6.5
  test_package:
    path: ../isolate_exec_test_package
